#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

# aws shit
export AWS_SDK_LOAD_CONFIG=1

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

_prepend () {
  local PATHTYPE DIR
  PATHTYPE=$1
  DIR=$2
  if [[ -d "$DIR" ]] ; then
    eval "$PATHTYPE=($DIR \$$PATHTYPE)"
  fi
}
_append () {
  local PATHTYPE DIR
  PATHTYPE=$1
  DIR=$2
  if [[ -d "$DIR" ]] ; then
    eval "$PATHTYPE=(\$$PATHTYPE $DIR)"
  fi
}

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{sbin,bin}
  /usr/{sbin,bin}
  /{sbin,bin}
  $path
)
manpath=(
  $(manpath)
)
# anonymous function for local bindings
function {
  local DIR
  for DIR in $(ls -d /usr/local/opt/*/libexec) ; do
    _prepend path $DIR/gnubin
    _prepend manpath $DIR/gnuman
  done;
}

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-g -i -M -R -w -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

#
# Convoy specific stuff
#

if [[ -e $HOME/.convoy ]] ; then
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

    _prepend path $HOME/code/convoyinc/ops/.tools

    export VAULT_CAPATH=/Users/$USER/code/convoyinc/ops/credentials/convoy-vault-ca.cert.pem
    # the below doesn't work due to golang ignoring OS dns while on VPN
    # export VAULT_ADDR=https://mcp.greypoint.co:8200
    export VAULT_ADDR=https://10.10.27.22:8200

    _append path /Applications/Postgres.app/Contents/Versions/latest/bin
    export PGHOST=localhost
    export PGPORT=5432

    path=(./node_modules/.bin $path)

    # kubectl/helm autocompletion
    if [ $commands[kubectl] ]; then source <(kubectl completion zsh); fi
    if [ $commands[helm] ]; then source <(helm completion zsh); fi
fi

#
# gcloud
#

_prepend path $HOME/bin/google-cloud-sdk/bin
if [ -f $HOME/bin/google-cloud-sdk/completion.zsh.inc ]; then . $HOME/bin/google-cloud-sdk/completion.zsh.inc; fi

#
# Things That Must Be Last
#

_prepend path $HOME/go/bin
_prepend path $HOME/bin
_prepend path $HOME/local/bin
_prepend path $HOME/.cargo/bin
