#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# misc options
setopt CLOBBER

# history
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_BY_COPY
unsetopt HIST_IGNORE_ALL_DUPS
unsetopt HIST_IGNORE_SPACE
unsetopt HIST_SAVE_NO_DUPS
export HISTFILE=~/.zhistory
export HISTSIZE=200000
export SAVEHIST=100000

# have autocorrect ignore stuff in relative paths
autoload -Uz add-zsh-hook
function _correct_ignore_relpaths {
  setopt local_options null_glob
  local p paths filenames
  typeset -a filenames
  paths=(${(M)path:#.*})
  for p in $paths ; do
    filenames+=($p/*(:t) $p/.*(:t))
  done
  export CORRECT_IGNORE="(${(j:|:)filenames})"
}
# dammit, I can't get zsh to recognize CORRECT_IGNORE
#_correct_ignore_relpaths
#add-zsh-hook chpwd _correct_ignore_relpaths

# make Control-R do history searches
bindkey '^R' history-incremental-pattern-search-backward

#if is-callable 'dircolors' ; then
#  if zstyle -t ':prezto:module:utility:ls' color; then
#    if [[ $TERM == *"256"* ]] ; then
#      eval "$(dircolors --sh /etc/DIR_COLORS.256color)"
#    fi
#  fi
#fi

# osx-specific crap
if [[ "$OSTYPE" == "darwin"* ]] && [[ "$UID" != 0 ]] ; then
  # ensure homebrew coreutils are installed
  brew list | grep -q coreutils &> /dev/null || echo -e '\n\n    You probably want to brew install coreutils, champ\n\n'
  alias crontab='VIM_CRONTAB=true EDITOR=vim crontab'
fi
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# general aliases
whence -f view &> /dev/null || alias view='vim -R'
alias sshpw='ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no'
alias atopd='sudo atop -l -d -D 2'
alias pip=pip3
alias python=python3
alias wtf='wtf -o'
alias redocker='$(aws-okta exec prod-ro -- aws ecr get-login --no-include-email)'
alias redockerw='$(aws-okta exec prod-rw -- aws ecr get-login --no-include-email)'

# functions functions functions
function fix_osx_dns_search {
  local ADAPTER
  networksetup -listallnetworkservices | tail -n+2 | while read ADAPTER ; do networksetup -setsearchdomains "$ADAPTER" internal.convoy.com convoy.com ; done
}

function mdless {
  local FILE=${1:=README.md}
  mdcat $FILE | less -r
}

# git stuff
function gc {
  git clone https://github.com/convoyinc/$1 ${2:-~/code/convoyinc}/$1 ; cd ${2:-~/code/convoyinc}/$1
}
alias gitwipe='git restore --staged . &> /dev/null && git restore . &> /dev/null && git clean -f -d &> /dev/null && git status'

# exports
export GITHUB_TOKEN=$(cat ~/.github-token)
# convenience envvars
export UARTI="https://packages.convoy.com/artifactory/api/npm/npm/"
export UARTIC="https://packages.convoy.com/artifactory/api/npm/convoy-npm/"
export UNPMJS="https://registry.npmjs.org/"
export ARTI="--registry=https://packages.convoy.com/artifactory/api/npm/npm/"
export ARTIC="--registry=https://packages.convoy.com/artifactory/api/npm/convoy-npm/"
export NPMJS="--registry=https://registry.npmjs.org/"

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/amyers/.shepherd/2019-09-23-artifactory-migration-iii/repos/convoyinc/twilio-webhook/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/amyers/.shepherd/2019-09-23-artifactory-migration-iii/repos/convoyinc/twilio-webhook/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/amyers/.shepherd/2019-09-23-artifactory-migration-iii/repos/convoyinc/twilio-webhook/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/amyers/.shepherd/2019-09-23-artifactory-migration-iii/repos/convoyinc/twilio-webhook/node_modules/tabtab/.completions/sls.zsh
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f /Users/amyers/.shepherd/2019-09-23-artifactory-migration-iii/repos/convoyinc/twilio-webhook/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/amyers/.shepherd/2019-09-23-artifactory-migration-iii/repos/convoyinc/twilio-webhook/node_modules/tabtab/.completions/slss.zsh

export YVM_DIR=/usr/local/opt/yvm
[ -r $YVM_DIR/yvm.sh ] && . $YVM_DIR/yvm.sh
