#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# misc options
setopt CLOBBER

# history
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_BY_COPY
unsetopt HIST_IGNORE_ALL_DUPS
unsetopt HIST_IGNORE_SPACE
unsetopt HIST_SAVE_NO_DUPS
export HISTFILE=~/.zhistory
export HISTSIZE=200000
export SAVEHIST=100000

# have autocorrect ignore stuff in relative paths
autoload -Uz add-zsh-hook
function _correct_ignore_relpaths {
  setopt local_options null_glob
  local p paths filenames
  typeset -a filenames
  paths=(${(M)path:#.*})
  for p in $paths ; do
    filenames+=($p/*(:t) $p/.*(:t))
  done
  export CORRECT_IGNORE="(${(j:|:)filenames})"
}
# dammit, I can't get zsh to recognize CORRECT_IGNORE
#_correct_ignore_relpaths
#add-zsh-hook chpwd _correct_ignore_relpaths

# make Control-R do history searches
bindkey '^R' history-incremental-pattern-search-backward

#if is-callable 'dircolors' ; then
#  if zstyle -t ':prezto:module:utility:ls' color; then
#    if [[ $TERM == *"256"* ]] ; then
#      eval "$(dircolors --sh /etc/DIR_COLORS.256color)"
#    fi
#  fi
#fi

# osx-specific crap
if [[ "$OSTYPE" == "darwin"* ]] && [[ "$UID" != 0 ]] ; then
  # ensure homebrew coreutils are installed
  brew list | grep -q coreutils &> /dev/null || echo -e '\n\n    You probably want to brew install coreutils, champ\n\n'
  alias crontab='VIM_CRONTAB=true EDITOR=vim crontab'
fi
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# general aliases
whence -f view &> /dev/null || alias view='vim -R'
alias sshpw='ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no'
alias atopd='sudo atop -l -d -D 2'
alias pip=pip3
alias python=python3
alias wtf='wtf -o'
alias redocker='$(aws-okta exec prod-ro -- aws ecr get-login --no-include-email)'
alias redockerw='$(aws-okta exec prod-rw -- aws ecr get-login --no-include-email)'
alias boatmurder='echo -e "\nBEFORE\n"; docker system df; echo -e "\nSTOPPING\n"; docker stop -t3 $(docker ps -a -q); echo -e "\nPRUNING\n"; docker system prune -a -f --volumes; echo -e "\nAFTER\n";  docker system df'
alias fixscr='displayplacer "id:5FA4EB08-E21C-1F68-8224-91170AE46DF8 res:2560x1440 hz:60 color_depth:8 scaling:off origin:(0,0) degree:0" "id:3B8ED8DD-ED24-F674-8846-7B33AF9315C0 res:1680x1050 color_depth:4 scaling:on origin:(-1680,160) degree:0" "id:C281C76C-B62C-E064-C876-9A82F0762BD7 res:2560x1440 hz:60 color_depth:8 scaling:off origin:(2560,0) degree:0"'
alias oman='man -M /usr/share/man'
alias wipecache='yarn cache clean && npm cache clean --force'
alias yarn='noglob yarn'
alias mdless='mdless -I -P'

# functions functions functions
function fix_osx_dns_search {
  local ADAPTER
  networksetup -listallnetworkservices | tail -n+2 | while read ADAPTER ; do networksetup -setsearchdomains "$ADAPTER" internal.convoy.com convoy.com ; done
}

# git stuff
function gc {
  git clone https://github.com/convoyinc/$1 ${2:-~/code/convoyinc}/$1 ; cd ${2:-~/code/convoyinc}/$1
}
function ggrep {
  git grep -P "$@" | grep -vP '^\.'
}
alias gitwipe='git restore --staged . &> /dev/null && git restore . &> /dev/null && git clean -f -d &> /dev/null && git status'
export GIT_PAGER='bat'
export BAT_STYLE='plain'
export BAT_THEME='ansi-light'

# exports
export GITHUB_TOKEN=$(cat ~/.github-token)
export CIRCLECI_TOKEN=$(cat ~/.circleci-token)
export NGROK_TOKEN=$(cat ~/.ngrok-token)
# convenience envvars
export UARTI="https://packages.convoy.com/artifactory/api/npm/npm/"
export UARTIC="https://packages.convoy.com/artifactory/api/npm/convoy-npm/"
export UARTIT="https://packages.convoy.com/artifactory/api/npm/test-npm/"
export UNPMJS="https://registry.npmjs.org/"
export ARTI="--registry=https://packages.convoy.com/artifactory/api/npm/npm/"
export ARTIC="--registry=https://packages.convoy.com/artifactory/api/npm/convoy-npm/"
export ARTIT="--registry=https://packages.convoy.com/artifactory/api/npm/test-npm/"
export NPMJS="--registry=https://registry.npmjs.org/"
# deployer-service exports
export DEPLOYER_GITHUB_APP_ID="$(cat ~/.deployer-service/deployer_github_app_id.txt)"
export DEPLOYER_GITHUB_PRIVATE_KEY_PATH=~/.deployer-service/deployer_github_private_key.pem
export DEPLOYER_GITHUB_PRIVATE_KEY="$(cat $DEPLOYER_GITHUB_PRIVATE_KEY_PATH)"
export DEPLOYER_CIRCLECI_API_TOKEN=${CIRCLECI_TOKEN}
export DEPLOYER_SLACK_OAUTH_TOKEN="$(cat ~/.deployer-service/deployer_circle_api_token.txt)"
export DEPLOYER_CHANNEL_DEV='#amyers-test'

# stuff needed for other things
export YVM_DIR=/usr/local/opt/yvm
[ -r $YVM_DIR/yvm.sh ] && . $YVM_DIR/yvm.sh
